### ISSUE TITLE
Busqueda pago mantenimiento

### ISSUE THREAD

**Issue by underwoodmario** [helhetkode/paseos#14]
¿Por que? D:
El numero de casa es muy pequeño para ocupar todo el ancho, por eso estaba al 50% compartiendo espacio con la calle, y no fue tan facil

![imagen](https://user-images.githubusercontent.com/27526943/39791848-5134ba20-5303-11e8-9704-7d6e8a8092af.png)

**Comment by Darkk820** [comment]
Sorry, así se queda :v

**Comment by underwoodmario** [comment]
¿Por que asi?
Insisto, se ve ridiculo el numero de casa en tanto espacio
