### ISSUE TITLE
Pago por adelantado

### ISSUE THREAD

**Issue by Darkk820** [helhetkode/paseos#17]
Cuando se hace un pago por adelantado, aparecen los meses a favor, pero no se ve reflejado en la tabla de pagos en la cuenta individual.

**Comment by underwoodmario** [comment]
Donde ves que si aparecen?

**Comment by underwoodmario** [comment]
Ah! Ya vi

**Comment by Darkk820** [comment]
Jaja ste men

**Comment by underwoodmario** [comment]
Pero si aparece...

**Comment by underwoodmario** [comment]
![imagen](https://user-images.githubusercontent.com/27526943/40032620-7af321ce-57ba-11e8-92a9-c86110b8aa06.png)
![imagen](https://user-images.githubusercontent.com/27526943/40032626-7da22b4a-57ba-11e8-87f7-58962554769f.png)
