### ISSUE TITLE
Problema de contencion

### ISSUE THREAD

**Issue by underwoodmario** [helhetkode/paseos#2]
Septiembre esta algo largo...

![imagen1](https://user-images.githubusercontent.com/27526943/39481971-eb745158-4d32-11e8-8058-bd56fccf095a.png)

**Comment by Darkk820** [comment]
Ya está solucionado

**Comment by underwoodmario** [comment]
Ya lo subiste? 
![imagen](https://user-images.githubusercontent.com/27526943/39555153-8b797bd8-4e3c-11e8-905b-1e6a2d584f9b.png)

**Comment by Darkk820** [comment]
No lo había subido
