### ISSUE TITLE
Mensaje reportes/mensajes

### ISSUE THREAD

**Issue by Darkk820** [helhetkode/paseos#27]
Agregar en la pantalla de inicio de mensajes y reportes una leyenda que diga que selecciones un reporte/mensaje para verlo.

**Comment by underwoodmario** [comment]
Te incluí un h1 con el texto "Modifica aqui" para que lo notes, ya ahi trabaja el mensaje que gustes y dale el estilo que prefieras, incluso el mismo si gustas xd
