### ISSUE TITLE
Pago por parcialidades

### ISSUE THREAD

**Issue by Darkk820** [helhetkode/paseos#31]

**Comment by underwoodmario** [comment]
Necesitamos que la pagina "Pago" siga ejecutando la insercion en la tabla de cuentas pero en deudas restara la cantidad insertada en el monto al monto de la misma, y las deudas seguiran apareciendo en el select siempre que este marcada como "Deudo" y sea menor a 0. Al ser 0, se marcara como "Pagado"

**Comment by underwoodmario** [comment]
Ya no es necesario
