### ISSUE TITLE
Fecha en reportes

### ISSUE THREAD

**Issue by Darkk820** [helhetkode/paseos#57]
Ya coloqué los <small>, sólo hace falta que muestren la fecha como en los mensajes.

**Comment by Darkk820** [comment]
Faltó la fecha en los reportes de los usuarios @underwoodmario

**Comment by underwoodmario** [comment]
Hace falta que incluyas donde voy a poner la fecha

**Comment by Darkk820** [comment]
Ya coloqué el <small> correspondiente, listo para que pongas la fecha.

**Comment by Darkk820** [comment]
<small>
